import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAppointments } from '@/hooks/useAppointments'
import { useAuth } from '@/hooks/useAuth'
import AppointmentForm from '@/components/appointment/AppointmentForm'
import Modal from '@/components/common/Modal'
import Sidebar from '@/components/layout/Sidebar'
import Header from '@/components/layout/Header'
import type { Appointment } from '@/types'

// We omit fields auto-generated by backend
type AppointmentFormValues = Omit<Appointment, '_id' | 'createdAt' | 'updatedAt'>

const BookAppointment = () => {
  const navigate = useNavigate()
  const { user } = useAuth()
  const { createAppointment } = useAppointments()
  const [showSuccessModal, setShowSuccessModal] = useState(false)

  if (!user) {
    // Redirect if no logged-in user
    navigate('/login')
    return null
  }

  const handleSubmit = async (values: AppointmentFormValues) => {
    try {
      // Ensure patient is the logged-in user and status is pending on creation
      const appointmentToCreate = {
        ...values,
        patient: user._id,
        status: 'pending' as const,
      }
      await createAppointment(appointmentToCreate)
      setShowSuccessModal(true)
    } catch (error) {
      console.error('Error creating appointment:', error)
    }
  }

  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      <div className="flex flex-1">
        <Sidebar />
        <main className="flex-1 p-8">
          <h1 className="text-2xl font-bold mb-6">Book Appointment</h1>
          <div className="max-w-2xl mx-auto">
            <AppointmentForm
              onSubmit={handleSubmit}
              onCancel={() => navigate('/patient-dashboard')}
            />
          </div>
          <Modal
            isOpen={showSuccessModal}
            onClose={() => {
              setShowSuccessModal(false)
              navigate('/my-appointments')
            }}
            title="Appointment Booked"
          >
            <p>Your appointment has been successfully booked!</p>
          </Modal>
        </main>
      </div>
    </div>
  )
}

export default BookAppointment
